### ISSUE TITLE
[Feature] Refactor Open Positions section of Careers page

### ISSUE THREAD

**Issue by aberner-va** [rise8-us/rise8-website#247]
### Acceptance Criteria
**Given** I am viewing the Careers page
**When** I scroll down to Open Positions
**Then** I should be able to navigate through all the open positions available and click to apply

### Notes
-

### Design Mockup
- https://drive.google.com/drive/folders/1arIqn8sJYXb41oBZETWAC4LUHiQOWHW4

**Comment by kaivarsson** [comment]
@aberner-va cut a few corners in the near-term with this one -- the way the breezy integration was first set up was with the public API (no auth token required) which gives minimal info. In order to get the description of the job, I'll need to set up the token auth, but I don't have access to breezy to do this. I should be able to when people are working again, but for now since I don't have any job descriptions i built it out with no accordion and the button on the right just opens the breezy page
