### ISSUE TITLE
[Feature] Redesign Blog page

### ISSUE THREAD

**Issue by aberner-va** [rise8-us/rise8-website#260]
### Acceptance Criteria
**Given** I am viewing the website
**When** I navigate to the Blog page
**Then** I should see it updated to match the new designs

### Notes
-

### Design Mockup
- https://drive.google.com/drive/folders/1arIqn8sJYXb41oBZETWAC4LUHiQOWHW4

**Comment by kaivarsson** [comment]
@aberner-va there are only 4 blogs in staging but there will be max 9 per page as in the design. i kept the general paging buttons at the bottom that we currently have in prod since the `view more` button in the design is a little ambiguous? when there are more than 18 are you only supposed to page one at a time instead of jumping around? 🤷‍♀
