### ISSUE TITLE
[Feature] Redesign Interior Blog page for text & video

### ISSUE THREAD

**Issue by aberner-va** [rise8-us/rise8-website#261]
### Acceptance Criteria
**Given** I am viewing the Blogs page
**When** I click on a blog post
**Then** I should be taken to a new page that matches the new designs

### Notes
- Two different designs for text vs video (though they look the same)

### Design Mockup
- Text: https://drive.google.com/drive/folders/1arIqn8sJYXb41oBZETWAC4LUHiQOWHW4
- Video: https://drive.google.com/drive/folders/1arIqn8sJYXb41oBZETWAC4LUHiQOWHW4

**Comment by kaivarsson** [comment]
@aberner-va only note on this one -- the transition note for the videos said they'd expand "on autoplay". not really sure what that meant since it felt weird to just start playing the video immediately when you get to the page (especially if it were to expand too), so it just expands when you start the video (and contracts when you pause it)
